# Generated by Django 3.0.2 on 2020-03-23 16:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('description', models.TextField(max_length=300)),
                ('year_of_release', models.CharField(blank=True, max_length=100)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('like_counts', models.IntegerField(default=0)),
                ('dislike_counts', models.IntegerField(default=0)),
                ('like', models.BooleanField(default=False)),
                ('dislike', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tvshows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('description', models.TextField(max_length=300)),
                ('year_of_release', models.CharField(max_length=100)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('season', models.CharField(blank=True, max_length=5)),
                ('episode', models.CharField(blank=True, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='tvshowgist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gists', models.TextField(max_length=300, null=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('worth_seeing', models.CharField(blank=True, max_length=20, null=True)),
                ('not_worth_seeing', models.CharField(blank=True, max_length=20, null=True)),
                ('tvshow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bollywood.Tvshows')),
                ('tvshow_dislike', models.ManyToManyField(blank=True, related_name='btvshow_dislikes', to=settings.AUTH_USER_MODEL)),
                ('tvshow_like', models.ManyToManyField(blank=True, related_name='btvshow_likes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bollyusertvshow', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MovieLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mybollylikesmovies', to='bollywood.Movies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mybollylikesusermovies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MovieDislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mybollydislikesmovies', to='bollywood.Movies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mybollydislikesusermovies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('tvshow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mybollylikestvshow', to='bollywood.Tvshows')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mybollylikesuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='gist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gists', models.TextField(max_length=300, null=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('worth_seeing', models.CharField(blank=True, max_length=20, null=True)),
                ('not_worth_seeing', models.CharField(blank=True, max_length=20, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bollywood.Movies')),
                ('movie_dislike', models.ManyToManyField(blank=True, related_name='bmovie_dislikes', to=settings.AUTH_USER_MODEL)),
                ('movie_like', models.ManyToManyField(blank=True, related_name='bmovie_likes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bollyusermovie', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('tvshow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mybollydislikestvshow', to='bollywood.Tvshows')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mybollydislikesuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
