# Generated by Django 3.0.2 on 2020-03-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hollywood', '0002_auto_20200229_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='dislikes',
            new_name='dislike_counts',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='likes',
            new_name='like_counts',
        ),
        migrations.RenameField(
            model_name='tvshows',
            old_name='dislikes',
            new_name='dislike_counts',
        ),
        migrations.RenameField(
            model_name='tvshows',
            old_name='likes',
            new_name='like_counts',
        ),
        migrations.AddField(
            model_name='movies',
            name='dislike',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movies',
            name='gists',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='like',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tvshows',
            name='dislike',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tvshows',
            name='gists',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='tvshows',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
