# Generated by Django 3.0.2 on 2020-03-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hollywood', '0003_auto_20200309_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='gist_dislike',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movies',
            name='gist_dislike_counts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movies',
            name='gist_like',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movies',
            name='gist_like_counts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tvshows',
            name='gist_dislike',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tvshows',
            name='gist_dislike_counts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tvshows',
            name='gist_like',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tvshows',
            name='gist_like_counts',
            field=models.IntegerField(default=0),
        ),
    ]
