# Generated by Django 3.0.2 on 2020-03-10 18:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hollywood', '0004_auto_20200309_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='gist_dislike',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='gist_dislike_counts',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='gist_like',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='gist_like_counts',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='gists',
        ),
        migrations.RemoveField(
            model_name='tvshows',
            name='gist_dislike',
        ),
        migrations.RemoveField(
            model_name='tvshows',
            name='gist_dislike_counts',
        ),
        migrations.RemoveField(
            model_name='tvshows',
            name='gist_like',
        ),
        migrations.RemoveField(
            model_name='tvshows',
            name='gist_like_counts',
        ),
        migrations.RemoveField(
            model_name='tvshows',
            name='gists',
        ),
        migrations.CreateModel(
            name='gist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gists', models.TextField(max_length=300, null=True)),
                ('gist_like_counts', models.IntegerField(default=0)),
                ('gist_dislike_counts', models.IntegerField(default=0)),
                ('gist_like', models.BooleanField(default=False)),
                ('gist_dislike', models.BooleanField(default=False)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hollywood.Movies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
