# Generated by Django 3.0.2 on 2020-03-13 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hollywood', '0005_auto_20200310_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='gist',
            name='tvshow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hollywood.Tvshows'),
        ),
    ]
