# Generated by Django 3.0.2 on 2020-03-15 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hollywood', '0007_tvshowgist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvshowgist',
            name='movie',
        ),
    ]
