# Generated by Django 3.0.2 on 2020-03-15 05:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hollywood', '0009_remove_gist_tvshow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshowgist',
            name='tvshow',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hollywood.Tvshows'),
            preserve_default=False,
        ),
    ]
