# Generated by Django 3.0.2 on 2020-03-17 17:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hollywood', '0010_auto_20200314_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gist',
            name='gist_dislike_counts',
        ),
        migrations.RemoveField(
            model_name='gist',
            name='gist_like_counts',
        ),
        migrations.RemoveField(
            model_name='tvshowgist',
            name='gist_dislike_counts',
        ),
        migrations.RemoveField(
            model_name='tvshowgist',
            name='gist_like_counts',
        ),
        migrations.RemoveField(
            model_name='gist',
            name='gist_dislike',
        ),
        migrations.AddField(
            model_name='gist',
            name='gist_dislike',
            field=models.ManyToManyField(blank=True, related_name='hmovie_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='gist',
            name='gist_like',
        ),
        migrations.AddField(
            model_name='gist',
            name='gist_like',
            field=models.ManyToManyField(blank=True, related_name='hmovie_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='tvshowgist',
            name='gist_dislike',
        ),
        migrations.AddField(
            model_name='tvshowgist',
            name='gist_dislike',
            field=models.ManyToManyField(blank=True, related_name='htvshow_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='tvshowgist',
            name='gist_like',
        ),
        migrations.AddField(
            model_name='tvshowgist',
            name='gist_like',
            field=models.ManyToManyField(blank=True, related_name='htvshow_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
