# Generated by Django 3.0.2 on 2020-03-18 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hollywood', '0011_auto_20200317_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='gist',
            name='not_worth_seeing',
            field=models.TextField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='gist',
            name='worth_seeing',
            field=models.TextField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='tvshowgist',
            name='not_worth_seeing',
            field=models.TextField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='tvshowgist',
            name='worth_seeing',
            field=models.TextField(blank=True, max_length=15, null=True),
        ),
    ]
