# Generated by Django 3.0.2 on 2020-03-18 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hollywood', '0013_auto_20200317_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gist',
            name='not_worth_seeing',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gist',
            name='worth_seeing',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tvshowgist',
            name='not_worth_seeing',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tvshowgist',
            name='worth_seeing',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
