# Generated by Django 3.0.2 on 2020-03-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hollywood', '0014_auto_20200317_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gist',
            name='not_worth_seeing',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='gist',
            name='worth_seeing',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='tvshowgist',
            name='not_worth_seeing',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='tvshowgist',
            name='worth_seeing',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
