# Generated by Django 3.0.2 on 2020-03-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hollywood', '0015_auto_20200317_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshowgist',
            name='not_worth_seeing',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tvshowgist',
            name='worth_seeing',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
