# Generated by Django 3.0.2 on 2020-03-19 19:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hollywood', '0017_auto_20200319_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvshows',
            name='dislike',
        ),
        migrations.AddField(
            model_name='tvshows',
            name='dislike',
            field=models.ManyToManyField(blank=True, related_name='htvshow_disslikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='tvshows',
            name='like',
        ),
        migrations.AddField(
            model_name='tvshows',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='htvshow_llikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
