# Generated by Django 3.0.2 on 2020-03-19 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hollywood', '0020_auto_20200319_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvshows',
            name='like_counts',
        ),
    ]
