# Generated by Django 3.0.2 on 2020-03-19 22:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hollywood', '0021_remove_tvshows_like_counts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvshows',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='tvshows',
            name='dislike_counts',
        ),
        migrations.RemoveField(
            model_name='tvshows',
            name='like',
        ),
        migrations.CreateModel(
            name='MovieLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mylikesmovies', to='hollywood.Movies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mylikesusermovies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MovieDislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mydislikesmovies', to='hollywood.Movies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mydislikesusermovies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
