# Generated by Django 3.0.2 on 2020-03-31 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hollywood', '0024_auto_20200329_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hollywoodmoviesuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tvshows',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hollywoodtvshowuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
