# Generated by Django 3.0.2 on 2020-04-23 00:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hollywood', '0025_auto_20200331_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='user',
        ),
        migrations.AddField(
            model_name='movies',
            name='user',
            field=models.ManyToManyField(null=True, related_name='hollywoodmoviesuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
