# Generated by Django 3.0.2 on 2020-04-23 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hollywood', '0026_auto_20200423_0113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='user',
        ),
        migrations.AddField(
            model_name='movies',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hollywoodmoviesuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
