# Generated by Django 3.0.2 on 2020-03-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gist', '0002_auto_20200229_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gist',
            old_name='dislikes',
            new_name='dislikes_counts',
        ),
        migrations.RenameField(
            model_name='gist',
            old_name='likes',
            new_name='likes_counts',
        ),
        migrations.AddField(
            model_name='gist',
            name='dislike',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gist',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
