# Generated by Django 3.0.2 on 2020-03-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gist', '0003_auto_20200309_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gist',
            name='gistImage',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
