# Generated by Django 3.0.2 on 2020-03-15 04:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gist', '0004_auto_20200309_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='tvshowGist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gists', models.TextField()),
                ('gistImage', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('likes_counts', models.IntegerField(default=0)),
                ('dislikes_counts', models.IntegerField(default=0)),
                ('gistDate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('like', models.BooleanField(default=False)),
                ('dislike', models.BooleanField(default=False)),
            ],
        ),
    ]
